version: "3"
services:
  upstore_be-dev:
    build:
      context: ./
      dockerfile: Dockerfile.development
    container_name: "upstore_be-dev"
    ports:
      - "${APP_PORT:-8080}:8080"
      - "${GRPC_PORT}:${GRPC_PORT}"
    environment:
      DB_URL: "${DB_URL}"
    volumes:
      - .:/go/src/app/
      - ./go.mod:/go/src/app/go.mod
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
